import { Product, Promotion, BranchLocation, ThemeConfig, DiscountCoupon, QuantityDiscountRule } from '../types';

export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    id: 'promo-2026',
    title: 'Indumentaria que aguanta el trabajo',
    subtitle: 'Catálogo digital de exhibición. Hombre, mujer, infantil y venta corporativa, con fichas de producto, talles, colores y promociones vigentes.',
    badge: 'TEMPORADA 2026',
    bannerImage: '/hero.jpg',
    tagFilter: 'Temporada 2026',
    active: true,
    associatedProductCodes: ['PAM-URB-01', 'PAM-URB-02', 'PAM-BOM-001', 'PAM-MUJ-01'],
    textColor: '#FFFFFF',
    fontSize: '72px',
    subtitleColor: '#DCD4C9',
    subtitleFontSize: '16px',
    primaryBtnText: 'VER CATÁLOGO',
  },
  {
    id: 'promo-corporativo',
    title: 'Dotaciones & Venta Mayorista',
    subtitle: 'Precios especiales por bulto y bordado institucional para empresas e industrias.',
    badge: 'DESCUENTOS POR VOLUMEN',
    bannerImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1600&q=80',
    categoryFilter: 'Venta Corporativa',
    tagFilter: 'Venta Corporativa',
    discountOnly: false,
    active: true,
    associatedProductCodes: ['PAM-IND-01', 'PAM-IND-03', 'PAM-IND-04', 'PAM-CAL-001'],
    textColor: '#FFFFFF',
    fontSize: '64px',
    subtitleColor: '#DCD4C9',
    subtitleFontSize: '16px',
    primaryBtnText: 'VENTA CORPORATIVA',
  },
  {
    id: 'promo-rural',
    title: 'Especial Campo & Tradición',
    subtitle: 'Bombachas de campo reforzadas, fajas y calzado rústico de máxima resistencia.',
    badge: '15% OFF CONTADO',
    bannerImage: 'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?auto=format&fit=crop&w=1600&q=80',
    tagFilter: 'Especial Campo',
    discountOnly: true,
    discountPercentage: 15,
    active: true,
    associatedProductCodes: ['PAM-BOM-002', 'PAM-MUJ-02', 'PMP-10007'],
    textColor: '#FFFFFF',
    fontSize: '64px',
    subtitleColor: '#DCD4C9',
    subtitleFontSize: '16px',
    primaryBtnText: 'VER ESPECIAL CAMPO',
  },
];

export const INITIAL_BRANCHES: BranchLocation[] = [
  {
    id: 'mza-ciudad',
    name: 'Pampero Ciudad de Mendoza',
    address: 'San Martín 477',
    zone: 'Ciudad de Mendoza',
    phone: '261 527-6713',
    hours: 'Lunes a Viernes 8:30 a 13:00 y 16:30 a 20:30 | Sábados 9:00 a 13:30',
    mapsUrl: 'https://maps.google.com/?q=San+Martin+477+Mendoza',
  },
  {
    id: 'mza-lujan',
    name: 'Pampero Luján de Cuyo',
    address: 'Patricios 384',
    zone: 'Luján de Cuyo',
    phone: '261 527-6713',
    hours: 'Lunes a Viernes 8:30 a 12:30 y 16:30 a 20:30 | Sábados 9:00 a 13:00',
    mapsUrl: 'https://maps.google.com/?q=Patricios+384+Lujan+de+Cuyo+Mendoza',
  },
];

export const INITIAL_THEME: ThemeConfig = {
  primaryColor: '#18231C',     // Deep Pine Green / Dark Forest
  accentColor: '#FDB813',      // Amarillo Pampero Oficial
  hoverAccentColor: '#E0A310', // Amarillo hover
  secondaryColor: '#DCD4C9',   // Warm Stone / Linen Border
  backgroundColor: '#F5F2EC',  // Warm off-white / canvas
  textColor: '#18231C',        // Primary text
  headerBgColor: '#18231C',    // Top bar & footer
  headerTextColor: '#F5F2EC',  // Header text
  seasonBadgeBg: '#18231C',    // Cuadrito de temporada fondo
  seasonBadgeText: '#F5F2EC',  // Cuadrito de temporada texto
  discountBadgeBg: '#FDB813',  // Cuadrito de descuento fondo (Amarillo oficial)
  discountBadgeText: '#18231C',// Cuadrito de descuento texto
  cardBgColor: '#ECE5DC',      // Fondo tarjetas producto
  cardBorderColor: '#DCD4C9',  // Borde tarjetas producto
  fontFamily: 'Montserrat',
  customLogoUrl: '/logo-oficial.png.png',
  logoUrl: '/logo-oficial.png.png',
  brandTagline: 'Catálogo digital de exhibición · Gran Mendoza',
  whatsappNumber: '5492615276713',
  instagramHandle: 'pamperogranmendoza',
  emailContact: 'pamperogranmendoza@gmail.com',
};

export const INITIAL_COUPONS: DiscountCoupon[] = [
  {
    id: 'coup-edemsa',
    code: 'edemsa12026',
    description: 'Descuento corporativo exclusivo EDEMSA - Mendoza',
    discountType: 'percentage',
    discountValue: 15,
    expiresAt: '2026-12-31',
    assignedCompany: 'EDEMSA',
    usageCount: 3,
    isActive: true,
  },
  {
    id: 'coup-pampero10',
    code: 'PAMPERO2026',
    description: 'Beneficio clientes registrados Pampero Mendoza',
    discountType: 'percentage',
    discountValue: 10,
    expiresAt: '2026-12-31',
    usageCount: 12,
    isActive: true,
  },
  {
    id: 'coup-bono25k',
    code: 'BONO25K',
    description: 'Bono fijo $25.000 para pedidos mayores a $200.000',
    discountType: 'fixed',
    discountValue: 25000,
    minOrderAmount: 200000,
    expiresAt: '2026-08-31',
    usageCount: 5,
    isActive: true,
  },
];

export const INITIAL_VOLUME_DISCOUNTS: QuantityDiscountRule[] = [
  {
    id: 'rule-corp-10',
    name: 'Venta Corporativa (+10 unidades)',
    minQuantity: 10,
    discountPercentage: 15,
    category: 'Venta Corporativa',
    subCategory: 'Todas',
    active: true,
    description: '15% OFF a partir de 10 unidades en compras de la línea corporativa e industrial',
  },
  {
    id: 'rule-general-20',
    name: 'Mayorista General (+20 unidades)',
    minQuantity: 20,
    discountPercentage: 20,
    category: 'Todas',
    subCategory: 'Todas',
    active: true,
    description: '20% de descuento directo en el pedido superando las 20 unidades totales',
  },
  {
    id: 'rule-bombachas-5',
    name: 'Especial Bombachas de Campo (5+ unid)',
    minQuantity: 5,
    discountPercentage: 10,
    category: 'Hombre',
    subCategory: 'Bombachas',
    active: true,
    description: '10% OFF automático llevando 5 o más bombachas tradicionales',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // --- 10 PRODUCTOS OFICIALES PAMPERO CON MÚLTIPLES FOTOS ---
  {
    id: "pam-bom-001",
    code: "PAM-BOM-001",
    name: "Bombacha de Campo Pampero Tradicional Olivera",
    category: "Hombre",
    section: "Rural",
    subCategory: "Bombachas",
    description: "La auténtica bombacha de campo Pampero confeccionada bajo estrictas normas de resistencia rural. Gabardina pesada 100% algodón de sarga reforzada, tiro alto tradicional con botones en botamanga para regular ajuste sobre la bota.",
    features: [
      "Tejido 100% algodón sarga pesada 8 oz de máxima durabilidad",
      "Triple costura de cadeneta en laterales y entrepiernas",
      "Botamanga clásica regulable con botones reforzados",
      "Pasacintos anchos aptos para cinto criollo o rastra",
      "Bolsillo relojero frontal y dos bolsillos ojal traseros con botón"
    ],
    price: 48500,
    corporatePrice: 41225,
    discountPercentage: 15,
    promotionTag: "Línea Campo Tradición",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=1000&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=1000&auto=format&fit=crop"
    ],
    availableColors: ["Beige", "Verde Oliva", "Azul Marino", "Negro"],
    availableSizes: ["38", "40", "42", "44", "46", "48"],
    sizeType: "numbers",
    specialSizeRanges: [
      {
        id: 'spec-bom-1',
        suffix: '-1',
        rangeLabel: 'Talles Especiales 50 al 60',
        sizes: ['50', '52', '54', '56', '58', '60'],
        price: 54900,
        corporatePrice: 46665,
      }
    ],
    inStock: true,
    isFeatured: true
  },
  {
    id: "pam-bom-002",
    code: "PAM-BOM-002",
    name: "Bombacha Pampero Zelaya Denim Reforzada",
    category: "Hombre",
    section: "Rural",
    subCategory: "Bombachas",
    description: "Versión moderna en denim de alta tenacidad que fusiona la comodidad del jean con el corte campero tradicional. Desarrollada para resistir jornadas intensas en bodega, campo y talleres mecánicos.",
    features: [
      "Denim 100% algodón 12 oz prelavado con proceso sanforizado",
      "Remaches de latón oxidado en esquinas de bolsillos",
      "Cintura anatómica forrada para evitar rozaduras",
      "Costuras a contratono con hilado de alta resistencia al desgarro"
    ],
    price: 52900,
    corporatePrice: 44965,
    discountPercentage: 15,
    promotionTag: "Lanzamiento 2026",
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1582552938357-32b906df40cb?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=1000&auto=format&fit=crop"
    ],
    availableColors: ["Azul Índigo", "Azul Oscuro", "Negro Lavado"],
    availableSizes: ["38", "40", "42", "44", "46", "48"],
    sizeType: "numbers",
    specialSizeRanges: [
      {
        id: 'spec-bom2-1',
        suffix: '-1',
        rangeLabel: 'Talles Especiales 50 al 58',
        sizes: ['50', '52', '54', '56', '58'],
        price: 59900,
        corporatePrice: 50900,
      }
    ],
    inStock: true,
    isFeatured: true
  },
  {
    id: "pam-cal-001",
    code: "PAM-CAL-001",
    name: "Botín de Seguridad Pampero Tronador Puntera Acero",
    category: "Venta Corporativa",
    section: "Industria",
    subCategory: "Calzado de Seguridad",
    isCorporateOnly: true,
    description: "Botín de seguridad para faena pesada e industria. Fabricado con cuero vacuno flor seleccionado, puntera de acero certificada IRAM 3610 y suela de poliuretano bidensidad inyectada directamente al corte.",
    features: [
      "Puntera de acero templado resistente a impactos de 200 Joules",
      "Cuero flor de primera calidad con tratamiento hidrófugo repelente de aceites",
      "Suela de poliuretano bidensidad antideslizante con estrías autolimpiantes",
      "Plantilla anatómica antimicótica con arco de descanso",
      "Certificación IRAM 3610 / Sello S Seguridad Argentina"
    ],
    price: 89900,
    corporatePrice: 76415,
    discountPercentage: 15,
    promotionTag: "Norma IRAM 3610",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?q=80&w=1000&auto=format&fit=crop"
    ],
    availableColors: ["Negro", "Marrón Petróleo"],
    availableSizes: ["38", "39", "40", "41", "42", "43", "44", "45", "46"],
    sizeType: "numbers",
    inStock: true,
    isFeatured: true
  },
  {
    id: "pam-cal-002",
    code: "PAM-CAL-002",
    name: "Borceguí Pampero Leñador 5909 Cuero Engrasado",
    category: "Hombre",
    section: "Industria",
    subCategory: "Calzado de Seguridad",
    description: "Borceguí de caña alta diseñado para trabajos en forestación, viñedos de montaña y terrenos irregulares. Confeccionado en cuero vacuno engrasado de 2.2 mm de espesor y cuello acolchado.",
    features: [
      "Cuero engrasado de alta absorción de choque mecánico",
      "Cuello y fuelle acolchados en vaqueta para ajuste suave al tobillo",
      "Ganchos pasacordón de bronce fundido pavonado antioxidante",
      "Suela cosida 360° de caucho nitrilo de alta resistencia a la tracción"
    ],
    price: 98500,
    corporatePrice: 83725,
    discountPercentage: 15,
    promotionTag: "Uso Extremo",
    image: "https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?q=80&w=1000&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?q=80&w=1000&auto=format&fit=crop"
    ],
    availableColors: ["Marrón Chocolate", "Suela Tostado", "Negro"],
    availableSizes: ["39", "40", "41", "42", "43", "44", "45"],
    sizeType: "numbers",
    inStock: true,
    isFeatured: true
  },
  {
    id: "pam-cal-003",
    code: "PAM-CAL-003",
    name: "Borceguí Pampero Orma Trabajo Pesado",
    category: "Hombre",
    section: "Industria",
    subCategory: "Calzado de Seguridad",
    description: "Calzado robusto de diseño ergonómico para uso continuo en logística, minería y metalúrgica. Brinda soporte óptimo en el arco plantar y protección contra impactos mecánicos.",
    features: [
      "Forro interno textil termorregulador transpirable",
      "Talón reforzado con cámara de aire para absorción de impacto anti-fatiga",
      "Tratamiento hidrorrepelente para tareas en ambientes húmedos",
      "Cordones trenzados de alta tenacidad con alma de poliamida"
    ],
    price: 94000,
    corporatePrice: 79900,
    discountPercentage: 15,
    promotionTag: "Línea Operativa",
    image: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?q=80&w=1000&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?q=80&w=1000&auto=format&fit=crop"
    ],
    availableColors: ["Negro", "Gris Plomo"],
    availableSizes: ["39", "40", "41", "42", "43", "44", "45", "46"],
    sizeType: "numbers",
    inStock: true,
    isFeatured: false
  },
  {
    id: "pam-cal-004",
    code: "PAM-CAL-004",
    name: "Zapato Pampero Clásico 1609 Suela Dieléctrica",
    category: "Hombre",
    section: "Industria",
    subCategory: "Calzado de Seguridad",
    description: "Zapato de trabajo de caña baja con propiedades dieléctricas para electricistas, operarios de subestaciones y mantenimiento industrial.",
    features: [
      "Suela dieléctrica sin componentes metálicos expuestos",
      "Resistencia certificada de aislación eléctrica hasta 1000V",
      "Horma amplia anatómica para jornadas completas de pie",
      "Plantilla interior extraíble lavable"
    ],
    price: 78500,
    corporatePrice: 66725,
    discountPercentage: 15,
    promotionTag: "Dieléctrico",
    image: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?q=80&w=1000&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1533867617858-e7b97e060509?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?q=80&w=1000&auto=format&fit=crop"
    ],
    availableColors: ["Negro"],
    availableSizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    sizeType: "numbers",
    inStock: true,
    isFeatured: false
  },
  {
    id: "pam-cam-001",
    code: "PAM-CAM-001",
    name: "Camisa de Trabajo Pampero Soler Gabardina",
    category: "Hombre",
    section: "Industria",
    subCategory: "Camisas de Trabajo",
    description: "La camisa de trabajo insigne de Pampero. Gabardina 100% algodón sarga pesada 6 oz mercerizada. Confeccionada con costura doble en todas las uniones y cartera con división portabirome.",
    features: [
      "Sarga de gabardina 100% algodón mercerizado 6 oz",
      "Dos bolsillos delanteros con cartera y botón de seguridad",
      "Bolsillo izquierdo con ranura especial portabirome/herramienta",
      "Canesú con fuelle trasero para amplitud de movimiento de brazos",
      "Botones termosellados irrompibles con hilo al tono"
    ],
    price: 41200,
    corporatePrice: 35020,
    discountPercentage: 15,
    promotionTag: "Clásico Pampero",
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=1000&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1603252109303-2751441dd157?q=80&w=1000&auto=format&fit=crop"
    ],
    availableColors: ["Azul Marino", "Verde Oliva", "Beige Arena", "Gris Topo", "Naranja"],
    availableSizes: ["38", "40", "42", "44", "46", "48", "50", "52"],
    sizeType: "numbers",
    inStock: true,
    isFeatured: true
  },
  {
    id: "pam-cam-002",
    code: "PAM-CAM-002",
    name: "Camisa Pampero Maizani Denim Trabajo",
    category: "Hombre",
    section: "Urbano",
    subCategory: "Camisas",
    isUnisex: true,
    description: "Camisa confeccionada en tela denim liviana de 6.5 oz con lavado stone wash suave. Diseñada para personal de campo, atención comercial técnica y uniforme corporativo moderno.",
    features: [
      "Denim 100% algodón 6.5 oz suavizado al tacto",
      "Broches metálicos a presión tipo perla resistentes",
      "Canesú delantero y trasero estilo campero tradicional",
      "Puños regulables con doble botón a presión"
    ],
    price: 45800,
    corporatePrice: 38930,
    discountPercentage: 15,
    promotionTag: "Línea Denim",
    image: "https://images.unsplash.com/photo-1578932750294-f5075e85f44a?q=80&w=1000&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1578932750294-f5075e85f44a?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1589310243389-96a5483213a8?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=1000&auto=format&fit=crop"
    ],
    availableColors: ["Azul Índigo Lavado", "Azul Oscuro"],
    availableSizes: ["CH", "M", "G", "MG", "XG", "XXG"],
    sizeType: "letters",
    inStock: true,
    isFeatured: false
  },
  {
    id: "pam-cam-003",
    code: "PAM-CAM-003",
    name: "Camisa Pampero Soler Oxford Cuello Inglés",
    category: "Hombre",
    section: "Urbano",
    subCategory: "Camisas",
    description: "Camisa formal para líneas de supervisión, directivos de planta y oficinas técnicas. Confección Oxford de hilado fino peinado con tratamiento anti-arrugas para fácil planchado.",
    features: [
      "Tela Oxford peinada 70% algodón / 30% poliéster",
      "Cuello estructurado resistente al quiebre",
      "Bolsillo plaqué frontal discreto en el pecho",
      "Corte regular fit ergonómico de máxima elegancia"
    ],
    price: 39500,
    corporatePrice: 33575,
    discountPercentage: 15,
    promotionTag: "Corporativo",
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?q=80&w=1000&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1000&auto=format&fit=crop"
    ],
    availableColors: ["Celeste Oxford", "Blanco Puro", "Azul Francia"],
    availableSizes: ["38", "40", "42", "44", "46", "48", "50"],
    sizeType: "numbers",
    inStock: true,
    isFeatured: false
  },
  {
    id: "pam-abr-001",
    code: "PAM-ABR-001",
    name: "Campera Pampero Ciré Rural Térmica Acolchada",
    category: "Hombre",
    section: "Rural",
    subCategory: "Abrigos",
    description: "Campera ultraliviana térmica para bajas temperaturas en viñedos y campo abierto. Tejido ciré microporoso impermeable y relleno de fibra siliconada térmica de alto rendimiento.",
    features: [
      "Exterior ciré repelente al viento y rocío matutino",
      "Acolchado térmico siliconado de 150 gramos por metro cuadrado",
      "Cierre frontal diente de perro reforzado con tirador ergonómico",
      "Bolsillos laterales con cremallera y dos bolsillos internos para celular o libreta",
      "Puños y cintura elásticos para retención de calor corporal"
    ],
    price: 84000,
    corporatePrice: 71400,
    discountPercentage: 15,
    promotionTag: "Térmica Ultraliviana",
    image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?q=80&w=1000&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1544022613-e87ca75a784a?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1548883354-7622d03aca27?q=80&w=1000&auto=format&fit=crop"
    ],
    availableColors: ["Negro", "Azul Marino", "Verde Militar", "Bordeaux"],
    availableSizes: ["CH", "M", "G", "MG", "XG", "XXG"],
    sizeType: "letters",
    inStock: true,
    isFeatured: true
  },
  // --- ACCESORIOS (Originales) ---
  {
    id: 'pmp-10005',
    code: 'PMP-10005',
    name: 'Bolsos y mochilas Pampero Clásico',
    category: 'Hombre',
    section: 'Accesorios',
    subCategory: 'Bolsos y Mochilas',
    description: 'Prenda de muestra del catálogo. Confección resistente, costuras reforzadas y terminaciones pensadas para uso intensivo. Las imágenes y descripciones definitivas se reemplazan al cargar el material real.',
    features: ['Tejido de lona pesada con recubrimiento hidrófugo', 'Costuras reforzadas con remaches de latón', 'Herrajes metálicos y correa acolchada'],
    price: 36000,
    corporatePrice: 30600,
    discountPercentage: 15,
    image: '/ph-1.jpg',
    availableColors: ['Arena', 'Negro', 'Azul trabajo'],
    availableSizes: ['Único'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'pmp-10006',
    code: 'PMP-10006',
    name: 'Bolsos y mochilas Pampero Reforzado',
    category: 'Hombre',
    section: 'Accesorios',
    subCategory: 'Bolsos y Mochilas',
    description: 'Diseño utilitario para transporte diario de herramientas o ropa de trabajo. Fondo rígido lavable y doble manija de sujeción.',
    features: ['Fondo reforzado antidesgaste', 'Bolsillo frontal organizador con cierre', 'Capacidad 35 litros'],
    price: 37500,
    corporatePrice: 31875,
    discountPercentage: 15,
    image: '/ph-2.jpg',
    availableColors: ['Arena', 'Gris piedra', 'Negro'],
    availableSizes: ['Único'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'pmp-10007',
    code: 'PMP-10007',
    name: 'Bolsos y mochilas Pampero Serie Campo',
    category: 'Hombre',
    section: 'Accesorios',
    subCategory: 'Bolsos y Mochilas',
    description: 'Bolsón de viaje y trabajo rural confeccionado en lona cordura Pampero con vivos de cuero rústico.',
    features: ['Lona cordura 1000D de alta tenacidad', 'Detalles en cuero vacuno natural', 'Cierres YKK reforzados'],
    price: 39000,
    corporatePrice: 33150,
    discountPercentage: 15,
    promotionTag: 'Especial Campo',
    image: '/ph-3.jpg',
    availableColors: ['Terracota', 'Verde oliva', 'Negro'],
    availableSizes: ['Único'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'pmp-10008',
    code: 'PMP-10008',
    name: 'Bolsos y mochilas Pampero Edición Especial',
    category: 'Hombre',
    section: 'Accesorios',
    subCategory: 'Bolsos y Mochilas',
    description: 'Edición conmemorativa con estampa histórica Pampero. Gran capacidad de carga y resistencia comprobada.',
    features: ['Diseño vintage exclusivo Pampero', 'Tiradores ergonómicos anatómicos', 'Resistente al agua y al polvo'],
    price: 40500,
    corporatePrice: 34425,
    discountPercentage: 15,
    image: '/ph-4.jpg',
    availableColors: ['Terracota', 'Azul trabajo', 'Arena'],
    availableSizes: ['Único'],
    inStock: true,
    isFeatured: true,
  },
  // --- HOMBRE - URBANO ---
  {
    id: 'p-001',
    code: 'PAM-URB-01',
    name: 'Campera Softshell Urbana Térmica',
    category: 'Hombre',
    section: 'Urbano',
    subCategory: 'Abrigos',
    description: 'Campera liviana rompevientos con interior micropolar térmico, puños ajustables y bolsillos termosellados.',
    features: ['Membrana repelente al agua', 'Interior micropolar abrigado', 'Capucha desmontable con cordón de ajuste'],
    price: 98500,
    corporatePrice: 84000,
    discountPercentage: 10,
    promotionTag: 'Temporada 2026',
    image: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Negro', 'Azul Marino', 'Verde Oliva'],
    availableSizes: ['CH', 'M', 'G', 'MG', 'XG'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'p-002',
    code: 'PAM-URB-02',
    name: 'Pantalón Cargo Urbano Gabardina Pesada',
    category: 'Hombre',
    section: 'Urbano',
    subCategory: 'Pantalones y bermudas',
    description: 'Pantalón con calce moderno, 6 bolsillos utilitarios reforzados y tejido 100% algodón prelavado.',
    features: ['Gabardina 8.5 oz suave y resistente', 'Costuras reforzadas con doble aguja', 'Bolsillos laterales con fuelle'],
    price: 64900,
    corporatePrice: 56000,
    discountPercentage: 0,
    promotionTag: 'Temporada 2026',
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Beige / Arena', 'Negro', 'Verde Militar'],
    availableSizes: ['38', '40', '42', '44', '46', '48', '50'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'p-003',
    code: 'PAM-URB-03',
    name: 'Camisa Leñadora Cuadrille Franela Pesada',
    category: 'Hombre',
    section: 'Urbano',
    subCategory: 'Camisas',
    description: 'Camisa clásica abrigada a cuadros, confeccionada en hilado peinado de franela de puro algodón.',
    features: ['100% algodón perchado suave', 'Botones reforzados de alta fijación', 'Bolsillos en pecho con solapa'],
    price: 52000,
    corporatePrice: 45000,
    discountPercentage: 15,
    promotionTag: 'Temporada 2026',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Rojo y Negro', 'Azul y Ocre', 'Verde y Tabaco'],
    availableSizes: ['M', 'G', 'MG', 'XG'],
    inStock: true,
    isFeatured: false,
  },
  {
    id: 'p-004',
    code: 'PAM-URB-04',
    name: 'Remera Algodón Pima Peinado Pampero Original',
    category: 'Hombre',
    section: 'Urbano',
    subCategory: 'Remeras',
    description: 'Remera cuello redondo básica con bordado discreto Pampero en el pecho. No encoge ni deforma.',
    features: ['Puro algodón 24/1 premium', 'Corte clásico con ribete reforzado', 'Costuras al tono'],
    price: 28900,
    corporatePrice: 24000,
    discountPercentage: 0,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Blanco', 'Gris Melange', 'Azul Petróleo', 'Negro'],
    availableSizes: ['CH', 'M', 'G', 'MG', 'XG', 'XXG'],
    inStock: true,
  },
  {
    id: 'p-005',
    code: 'PAM-URB-05',
    name: 'Zapatilla Urbana Outdoor Pampero Trek',
    category: 'Hombre',
    section: 'Urbano',
    subCategory: 'Calzado',
    description: 'Calzado híbrido para asfalto y tierra, suela de caucho vulcanizado antideslizante y capellada transpirable.',
    features: ['Puntera de goma protectora', 'Plantilla acolchada anti-fatiga', 'Cordones tubulares de alta tracción'],
    price: 89000,
    corporatePrice: 77000,
    discountPercentage: 20,
    promotionTag: 'Temporada 2026',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Marrón Tabaco', 'Gris Asfalto'],
    availableSizes: ['39', '40', '41', '42', '43', '44', '45'],
    inStock: true,
    isFeatured: true,
  },

  // --- HOMBRE - INDUSTRIA ---
  {
    id: 'p-006',
    code: 'PAM-IND-01',
    name: 'Mameluco de Trabajo Pampero Gabardina Homologado',
    category: 'Hombre',
    section: 'Industria',
    subCategory: 'Indumentaria profesional',
    description: 'El clásico mameluco industrial Pampero con triple costura, elásticos laterales y cierre doble deslizador.',
    features: ['Gabardina Sanforizada 100% algodón 8 oz', 'Norma IRAM de resistencia mecánica', 'Bolsillos porta herramientas y pasamanos'],
    price: 78500,
    corporatePrice: 65000,
    discountPercentage: 0,
    promotionTag: 'Venta Corporativa',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Azul Marino', 'Naranja Vial', 'Verde Petróleo', 'Gris'],
    availableSizes: ['46', '48', '50', '52', '54', '56', '58', '60'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'p-007',
    code: 'PAM-IND-02',
    name: 'Borcego de Seguridad Pampero Bravo c/ Puntera de Acero',
    category: 'Hombre',
    section: 'Industria',
    subCategory: 'Calzado',
    description: 'Borcego petrolero y de obra con cuero vacuno flor seleccionado, suela dieléctrica y puntera de acero certificada.',
    features: ['Suela PU bidensidad inyectada', 'Certificación IRAM 3610', 'Tratamiento hidrófugo resistente a aceites'],
    price: 112000,
    corporatePrice: 96000,
    discountPercentage: 10,
    promotionTag: 'Temporada 2026',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Negro', 'Marrón Cuero'],
    availableSizes: ['38', '39', '40', '41', '42', '43', '44', '45', '46'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'p-008',
    code: 'PAM-IND-03',
    name: 'Traje de Lluvia Impermeable Pesado PVC Pampero',
    category: 'Hombre',
    section: 'Industria',
    subCategory: 'Impermeables',
    description: 'Conjunto chaqueta y pantalón termosellado de alta tenacidad para trabajos bajo lluvia intensa e intemperie.',
    features: ['100% impermeable con costuras dieléctricas', 'Solapa con broches de presión y capucha oculta', 'Ventilación dorsal'],
    price: 49500,
    corporatePrice: 42000,
    discountPercentage: 0,
    promotionTag: 'Venta Corporativa',
    image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Amarillo Vial', 'Azul Oscuro'],
    availableSizes: ['M', 'G', 'MG', 'XG', 'XXG'],
    inStock: true,
  },
  {
    id: 'p-009',
    code: 'PAM-IND-04',
    name: 'Chaleco de Seguridad Alta Visibilidad con Cintas 3M',
    category: 'Hombre',
    section: 'Industria',
    subCategory: 'Elementos de Protección',
    description: 'Chaleco reflectivo reglamentario con bandas prismáticas de alta reflexión nocturna y cierre frontal.',
    features: ['Tejido respirable 100% poliéster flúor', 'Bandas reflectivas de 5 cm 3M Scotchlite', 'Bolsillos porta lapicera e identificación'],
    price: 18900,
    corporatePrice: 14500,
    discountPercentage: 15,
    promotionTag: 'Venta Corporativa',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Naranja Flúor', 'Amarillo Flúor'],
    availableSizes: ['G', 'MG', 'XG'],
    inStock: true,
  },

  // --- HOMBRE - RURAL ---
  {
    id: 'p-010',
    code: 'PAM-RUR-01',
    name: 'Bombacha de Campo Pampero Tradicional Lisa',
    category: 'Hombre',
    section: 'Rural',
    subCategory: 'Bombachas',
    description: 'La emblemática bombacha criolla Pampero. Tiro alto, tabla cosida, bolsillo relojero y botamanga con botón.',
    features: ['100% algodón reforzado 8 oz', 'Rodilleras interiores y atraques de seguridad', 'Corte amplio tradicional de máxima comodidad'],
    price: 58000,
    corporatePrice: 49900,
    discountPercentage: 10,
    promotionTag: 'Especial Campo',
    image: 'https://images.unsplash.com/photo-1475178626620-a4d074967452?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Beige Campo', 'Negro', 'Azul Marino', 'Verde Seco'],
    availableSizes: ['38', '40', '42', '44', '46', '48', '50', '52', '54', '56'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'p-011',
    code: 'PAM-RUR-02',
    name: 'Boina Vasca Hilada Fina Pampero Gran Mendoza',
    category: 'Hombre',
    section: 'Rural',
    subCategory: 'Boinas y Fajas',
    description: 'Boina campera de pura lana tejida con badana de cuero y bordado conmemorativo Pampero.',
    features: ['100% lana natural termorreguladora', 'Badana interna de cuero genuino', 'Vuelo 28cm y 30cm'],
    price: 24500,
    corporatePrice: 21000,
    discountPercentage: 0,
    promotionTag: 'Especial Campo',
    image: 'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Negro', 'Gris Topo', 'Azul Noche'],
    availableSizes: ['56', '58', '60'],
    inStock: true,
  },
  {
    id: 'p-012',
    code: 'PAM-RUR-03',
    name: 'Bota de Cuero Engrasado Suela de Goma Rural',
    category: 'Hombre',
    section: 'Rural',
    subCategory: 'Calzado',
    description: 'Bota campera media caña de cuero graso resistente al agua, barro y espinillo, cosida a mano.',
    features: ['Cuero flor engrasado de 2.2mm', 'Suela de caucho pegada y cosida vira al tono', 'Tiradores laterales reforzados'],
    price: 125000,
    corporatePrice: 109000,
    discountPercentage: 15,
    promotionTag: 'Temporada 2026',
    image: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Marrón Engrasado', 'Suela Natural'],
    availableSizes: ['39', '40', '41', '42', '43', '44', '45'],
    inStock: true,
  },

  // --- HOMBRE - AVENTURA & ACCESORIOS ---
  {
    id: 'p-013',
    code: 'PAM-ACC-01',
    name: 'Mochila Estanca Pampero DryBag 35L Impermeable',
    category: 'Hombre',
    section: 'Accesorios',
    subCategory: 'Bolsos Estancos',
    description: 'Bolso mochila 100% hermético con cierre roll-top para travesías, pesca, río y cordillera mendocina.',
    features: ['Lona PVC 500D sellada por alta frecuencia', 'Arnés ergonómico acolchado para hombros', 'Bolsillo frontal impermeable con cierre estanco'],
    price: 68000,
    corporatePrice: 58000,
    discountPercentage: 10,
    promotionTag: 'Temporada 2026',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Amarillo de Seguridad', 'Negro Mate', 'Rojo'],
    availableSizes: ['35 Litros'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'p-014',
    code: 'PAM-ACC-02',
    name: 'Cinto de Cuero Curtido Crudo y Hebilla Zamak',
    category: 'Hombre',
    section: 'Accesorios',
    subCategory: 'Billeteras y Cintos',
    description: 'Cinturón robusto de cuero vacuno legítimo de 40mm de ancho con hebilla de alta resistencia.',
    features: ['Puro cuero vacuno espesor 3.8mm', 'Hebilla fundición Zamak niquelada o envejecida', 'Puntada al tono con hilo encerado'],
    price: 21900,
    corporatePrice: 18000,
    discountPercentage: 0,
    promotionTag: 'Temporada 2026',
    image: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Suela', 'Negro', 'Marrón Chocolate'],
    availableSizes: ['90cm', '100cm', '110cm', '120cm'],
    inStock: true,
  },

  // --- MUJER - URBANO & RURAL & INDUSTRIA ---
  {
    id: 'p-015',
    code: 'PAM-MUJ-01',
    name: 'Campera Parka Térmica Mujer Pampero Acolchada',
    category: 'Mujer',
    section: 'Urbano',
    subCategory: 'Camperas y Sacos',
    description: 'Parka con corte entallado femenino, relleno térmico siliconado ultra liviano y capucha con detalle desmontable.',
    features: ['Repelente al agua y viento cordillerano', 'Interior forrado en tafeta suave', 'Cintura ajustable con tancas interiores'],
    price: 105000,
    corporatePrice: 89000,
    discountPercentage: 15,
    promotionTag: 'Temporada 2026',
    image: 'https://images.unsplash.com/photo-1539533018447-63fcce667883?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Bordeaux', 'Negro', 'Verde Musgo'],
    availableSizes: ['XCH', 'CH', 'M', 'G', 'MG'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'p-016',
    code: 'PAM-MUJ-02',
    name: 'Bombacha de Campo Mujer Corte Femenino Elastizada',
    category: 'Mujer',
    section: 'Rural',
    subCategory: 'Bombachas',
    description: 'Bombacha con spandex para máximo confort y flexibilidad. Tiro medio-alto con ajuste perfecto a la cintura.',
    features: ['Gabardina 97% algodón 3% elastano', 'Bolsillos laterales y traseros con ojal', 'Presillas anchas para cinto o faja'],
    price: 59500,
    corporatePrice: 51000,
    discountPercentage: 10,
    promotionTag: 'Especial Campo',
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Arena', 'Azul Marino', 'Gris Cemento', 'Verde Oliva'],
    availableSizes: ['36', '38', '40', '42', '44', '46'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'p-017',
    code: 'PAM-MUJ-03',
    name: 'Borcego Femenino Industrial Pampero Lady Pro',
    category: 'Mujer',
    section: 'Industria',
    subCategory: 'Indumentaria y Calzado',
    description: 'Calzado de seguridad industrial desarrollado específicamente sobre horma femenina para total ergonomía y ligereza.',
    features: ['Puntera de composite ultraliviana (no conduce frío ni electricidad)', 'Suela antideslizante con shock absorber', 'Cuero nobuck hidrófugo'],
    price: 108000,
    corporatePrice: 92000,
    discountPercentage: 10,
    promotionTag: 'Temporada 2026',
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Negro c/ detalles Rosa', 'Marrón Suelo'],
    availableSizes: ['35', '36', '37', '38', '39', '40', '41'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'p-018',
    code: 'PAM-MUJ-04',
    name: 'Cartera Matera Cuero Genuino Pampero',
    category: 'Mujer',
    section: 'Accesorios',
    subCategory: 'Bolsos y Carteras',
    description: 'Bolso matero artesanal de cuero vacuno curtido vegetal con división acolchada para termo Stanley de 1.4L y mate.',
    features: ['100% cuero argentino de primera selección', 'Herrajes metálicos reforzados', 'Correa ancha regulable'],
    price: 49000,
    corporatePrice: 42000,
    discountPercentage: 0,
    promotionTag: 'Temporada 2026',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Suela Clásica', 'Marrón Moro'],
    availableSizes: ['Único'],
    inStock: true,
  },

  // --- INFANTIL ---
  {
    id: 'p-019',
    code: 'PAM-INF-01',
    name: 'Pantalón Escolar Reforzado Pampero Junior',
    category: 'Infantil',
    section: 'Línea Niños',
    subCategory: 'Vuelta al cole',
    description: 'Pantalón colegial ultra resistente a los juegos y roces. Rodilleras reforzadas y cintura con elástico interno regulable.',
    features: ['Sarga acrílico-algodón anti-manchas y fácil planchado', 'Costuras triples indestructibles', 'Bolsillos laterales'],
    price: 36000,
    corporatePrice: 31000,
    discountPercentage: 15,
    promotionTag: 'Temporada 2026',
    image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Azul Marino Escolar', 'Gris Topo'],
    availableSizes: ['6', '8', '10', '12', '14', '16'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'p-020',
    code: 'PAM-INF-02',
    name: 'Guardapolvo Escolar Recto Pampero Blanco',
    category: 'Infantil',
    section: 'Línea Niños',
    subCategory: 'Vuelta al cole',
    description: 'El clásico guardapolvo escolar argentino con tela Arciel de alta durabilidad, botones cosidos con atraque y bolsillos amplios.',
    features: ['Tejido Arciel de INTI homologado', 'Blanqueado permanente y secado rápido', 'Cinto trasero de ajuste'],
    price: 29500,
    corporatePrice: 25000,
    discountPercentage: 0,
    promotionTag: 'Temporada 2026',
    image: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Blanco Puro'],
    availableSizes: ['6', '8', '10', '12', '14', '16'],
    inStock: true,
  },
  {
    id: 'p-021',
    code: 'PAM-INF-03',
    name: 'Zapatilla Infantil Colegial Reforzada Cuero',
    category: 'Infantil',
    section: 'Línea Niños',
    subCategory: 'Calzado',
    description: 'Zapatilla escolar con puntera reforzada de goma y ajuste con abrojos dobles para calce rápido y seguro.',
    features: ['Capellada de cuero vacuno resistente', 'Suela de goma antideslizante blanca no mancha', 'Plantilla acolchada antibacteriana'],
    price: 48900,
    corporatePrice: 42000,
    discountPercentage: 10,
    promotionTag: 'Temporada 2026',
    image: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Negro Colegial', 'Blanco'],
    availableSizes: ['28', '29', '30', '31', '32', '33', '34', '35', '36'],
    inStock: true,
    isFeatured: true,
  },

  // --- VENTA CORPORATIVA ---
  {
    id: 'p-022',
    code: 'PAM-CORP-01',
    name: 'Camisa de Trabajo Pampero Corporativa Doble Bolsillo',
    category: 'Venta Corporativa',
    section: 'Empresas & Dotaciones',
    subCategory: 'Camisas',
    description: 'Camisa homologada para dotaciones de personal técnico y operativo. Ideal para bordado o estampado de logo empresarial.',
    features: ['Sarga 100% algodón 6.5 oz respirable', 'Bolsillos con tapa y traba para lapicera', 'Botones de pasta de alta durabilidad al lavado industrial'],
    price: 43000,
    corporatePrice: 34500,
    discountPercentage: 0,
    promotionTag: 'Venta Corporativa',
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Azul Marino', 'Gris Plomo', 'Beige', 'Verde Botella'],
    availableSizes: ['38', '40', '42', '44', '46', '48', '50', '52', '54'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'p-023',
    code: 'PAM-CORP-02',
    name: 'Pantalón de Trabajo Cargo Pampero Reforzado Corporativo',
    category: 'Venta Corporativa',
    section: 'Empresas & Dotaciones',
    subCategory: 'Pantalones',
    description: 'Pantalón de dotación con costura doble y triple atraque en zonas de mayor tracción. Resiste más de 200 lavados industriales.',
    features: ['100% algodón gabardina pesada sanforizada', 'Bolsillos traseros con botones y bolsillos cargo', 'Cintura con pasacintos anchos'],
    price: 52000,
    corporatePrice: 41000,
    discountPercentage: 0,
    promotionTag: 'Venta Corporativa',
    image: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Azul Marino', 'Gris Oscuro', 'Negro', 'Beige'],
    availableSizes: ['38', '40', '42', '44', '46', '48', '50', '52', '54', '56'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'p-024',
    code: 'PAM-CORP-03',
    name: 'Campera Térmica Truker Petrolera Ignífuga y Antiestática',
    category: 'Venta Corporativa',
    section: 'Empresas & Dotaciones',
    subCategory: 'Abrigos',
    description: 'Abrigo técnico para minería, petróleo y frío extremo en alta montaña con bandas refractarias de 50mm.',
    features: ['Tejido exterior rip-stop resinado impermeable', 'Guata térmica siliconada 200g y forrería matelassé', 'Certificación IRAM y resistencia a hidrocarburos'],
    price: 135000,
    corporatePrice: 112000,
    discountPercentage: 15,
    promotionTag: 'Venta Corporativa',
    image: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Azul Marino con Flúor', 'Rojo con Bandas 3M'],
    availableSizes: ['CH', 'M', 'G', 'MG', 'XG', 'XXG', 'XXXG'],
    inStock: true,
    isFeatured: true,
  },
  {
    id: 'p-025',
    code: 'PAM-CORP-04',
    name: 'Casco de Seguridad Pampero Clase A con Arnés a Cremallera',
    category: 'Venta Corporativa',
    section: 'Empresas & Dotaciones',
    subCategory: 'Seguridad',
    description: 'Casco de protección industrial de polietileno de alta densidad con ranuras para protección auditiva y facial.',
    features: ['Certificación IRAM 3620 Tipo 1 Clase A/B', 'Arnés textil con regulación tipo ratchet', 'Banda antisudor lavable'],
    price: 16500,
    corporatePrice: 12800,
    discountPercentage: 0,
    promotionTag: 'Venta Corporativa',
    image: 'https://images.unsplash.com/photo-1578873375972-02656910609f?auto=format&fit=crop&w=800&q=80',
    availableColors: ['Blanco', 'Amarillo', 'Azul', 'Rojo', 'Verde', 'Naranja'],
    availableSizes: ['Ajustable Universal'],
    inStock: true,
  },
];

